import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import ClientSideProviderTest from "@/components/ClientSideProviderTest";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Root Layout Component wraps around all route files inside the application
// it ensures a consistent layout for all routes within the application
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-default-bg text-default-text">
        {/* Provider Component Wrapper */}
        {/* if you wrap your application with a Client Component, the Server Child Components stay Server Components */}
        <ClientSideProviderTest>
          {/* main container */}
          <div className="m-auto flex min-h-screen w-[1536px] flex-col justify-between m2xl:w-[1366px] m1xl:w-[1280px] mxl:w-[1024px] mxl:px-[20px] mlg:w-[768px] mmd:w-[640px] msm:w-[475px] mxsm:w-[380px]">
            <Navbar />

            {/* components passed to the Root Layout */}
            {children}

            <Footer />
          </div>
        </ClientSideProviderTest>
      </body>
    </html>
  );
}
